# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DSOX4024A_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(502, 637)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 60, 481, 521))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(10, 10, 431, 321))
        self.widget.setObjectName("widget")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 130, 421, 151))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_Model = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Model.sizePolicy().hasHeightForWidth())
        self.lineEdit_Model.setSizePolicy(sizePolicy)
        self.lineEdit_Model.setObjectName("lineEdit_Model")
        self.gridLayout_2.addWidget(self.lineEdit_Model, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_Manufacturer = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Manufacturer.sizePolicy().hasHeightForWidth())
        self.lineEdit_Manufacturer.setSizePolicy(sizePolicy)
        self.lineEdit_Manufacturer.setObjectName("lineEdit_Manufacturer")
        self.gridLayout_2.addWidget(self.lineEdit_Manufacturer, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.lineEdit_SoftVersion = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_SoftVersion.sizePolicy().hasHeightForWidth())
        self.lineEdit_SoftVersion.setSizePolicy(sizePolicy)
        self.lineEdit_SoftVersion.setObjectName("lineEdit_SoftVersion")
        self.gridLayout_2.addWidget(self.lineEdit_SoftVersion, 3, 2, 1, 1)
        self.label_SN = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_SN.sizePolicy().hasHeightForWidth())
        self.label_SN.setSizePolicy(sizePolicy)
        self.label_SN.setObjectName("label_SN")
        self.gridLayout_2.addWidget(self.label_SN, 2, 0, 1, 1)
        self.lineEdit_SN = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_SN.sizePolicy().hasHeightForWidth())
        self.lineEdit_SN.setSizePolicy(sizePolicy)
        self.lineEdit_SN.setObjectName("lineEdit_SN")
        self.gridLayout_2.addWidget(self.lineEdit_SN, 2, 2, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 421, 85))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 1, 0, 1, 1)
        self.lineEdit_PORT = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_PORT.setObjectName("lineEdit_PORT")
        self.gridLayout.addWidget(self.lineEdit_PORT, 1, 1, 1, 1)
        self.lineEdit_IP = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_IP.setObjectName("lineEdit_IP")
        self.gridLayout.addWidget(self.lineEdit_IP, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 2, 0, 1, 1)
        self.lineEdit_BUFSIZE = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_BUFSIZE.setObjectName("lineEdit_BUFSIZE")
        self.gridLayout.addWidget(self.lineEdit_BUFSIZE, 2, 1, 1, 1)
        self.pushButton_connect = QtWidgets.QPushButton(self.widget)
        self.pushButton_connect.setGeometry(QtCore.QRect(220, 100, 91, 27))
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.pushButton_disconnect = QtWidgets.QPushButton(self.widget)
        self.pushButton_disconnect.setGeometry(QtCore.QRect(104, 100, 91, 27))
        self.pushButton_disconnect.setObjectName("pushButton_disconnect")
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.pushButton_send_setup = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_send_setup.setGeometry(QtCore.QRect(320, 410, 131, 32))
        self.pushButton_send_setup.setObjectName("pushButton_send_setup")
        self.textEdit_command = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_command.setGeometry(QtCore.QRect(10, 70, 441, 331))
        self.textEdit_command.setObjectName("textEdit_command")
        self.lineEdit_Setup = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_Setup.setGeometry(QtCore.QRect(10, 30, 321, 21))
        self.lineEdit_Setup.setObjectName("lineEdit_Setup")
        self.pushButton_select = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_select.setGeometry(QtCore.QRect(340, 30, 113, 32))
        self.pushButton_select.setObjectName("pushButton_select")
        self.pushButton_save = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_save.setGeometry(QtCore.QRect(200, 410, 113, 32))
        self.pushButton_save.setObjectName("pushButton_save")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 321, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_command = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_command.setGeometry(QtCore.QRect(10, 450, 311, 31))
        self.lineEdit_command.setObjectName("lineEdit_command")
        self.pushButton_send_command = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_send_command.setGeometry(QtCore.QRect(320, 450, 131, 32))
        self.pushButton_send_command.setObjectName("pushButton_send_command")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.radioButton_save = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_save.setEnabled(False)
        self.radioButton_save.setGeometry(QtCore.QRect(10, 10, 61, 22))
        self.radioButton_save.setObjectName("radioButton_save")
        self.radioButton_running = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_running.setEnabled(False)
        self.radioButton_running.setGeometry(QtCore.QRect(80, 10, 81, 22))
        self.radioButton_running.setObjectName("radioButton_running")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setEnabled(False)
        self.groupBox.setGeometry(QtCore.QRect(170, 0, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.radioButton_ain0 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_ain0.setGeometry(QtCore.QRect(10, 10, 49, 20))
        self.radioButton_ain0.setObjectName("radioButton_ain0")
        self.radioButton_ain1 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_ain1.setGeometry(QtCore.QRect(70, 10, 51, 22))
        self.radioButton_ain1.setObjectName("radioButton_ain1")
        self.radioButton_ain2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_ain2.setGeometry(QtCore.QRect(130, 10, 51, 22))
        self.radioButton_ain2.setObjectName("radioButton_ain2")
        self.radioButton_ain3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_ain3.setGeometry(QtCore.QRect(190, 10, 51, 22))
        self.radioButton_ain3.setObjectName("radioButton_ain3")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 210, 461, 252))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_datalength = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_datalength.setObjectName("lineEdit_datalength")
        self.gridLayout_4.addWidget(self.lineEdit_datalength, 6, 1, 1, 1)
        self.checkBox_manual = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_manual.setObjectName("checkBox_manual")
        self.gridLayout_4.addWidget(self.checkBox_manual, 4, 0, 1, 1)
        self.lineEdit_200k = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_200k.setObjectName("lineEdit_200k")
        self.gridLayout_4.addWidget(self.lineEdit_200k, 3, 1, 1, 1)
        self.progressBar_200k = QtWidgets.QProgressBar(self.gridLayoutWidget_4)
        self.progressBar_200k.setMaximum(100)
        self.progressBar_200k.setProperty("value", 1)
        self.progressBar_200k.setTextVisible(True)
        self.progressBar_200k.setObjectName("progressBar_200k")
        self.gridLayout_4.addWidget(self.progressBar_200k, 3, 2, 1, 1)
        self.label_storeddata = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_storeddata.setObjectName("label_storeddata")
        self.gridLayout_4.addWidget(self.label_storeddata, 0, 1, 1, 1)
        self.lineEdit_20k = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_20k.setObjectName("lineEdit_20k")
        self.gridLayout_4.addWidget(self.lineEdit_20k, 2, 1, 1, 1)
        self.progressBar_2k = QtWidgets.QProgressBar(self.gridLayoutWidget_4)
        self.progressBar_2k.setProperty("value", 0)
        self.progressBar_2k.setObjectName("progressBar_2k")
        self.gridLayout_4.addWidget(self.progressBar_2k, 1, 2, 1, 1)
        self.progressBar_20k = QtWidgets.QProgressBar(self.gridLayoutWidget_4)
        self.progressBar_20k.setProperty("value", 0)
        self.progressBar_20k.setObjectName("progressBar_20k")
        self.gridLayout_4.addWidget(self.progressBar_20k, 2, 2, 1, 1)
        self.lineEdit_man = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_man.setObjectName("lineEdit_man")
        self.gridLayout_4.addWidget(self.lineEdit_man, 4, 1, 1, 1)
        self.lineEdit_2k = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_2k.setAutoFillBackground(False)
        self.lineEdit_2k.setObjectName("lineEdit_2k")
        self.gridLayout_4.addWidget(self.lineEdit_2k, 1, 1, 1, 1)
        self.label_datalength = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_datalength.setObjectName("label_datalength")
        self.gridLayout_4.addWidget(self.label_datalength, 6, 0, 1, 1)
        self.label_gainscale = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_gainscale.setObjectName("label_gainscale")
        self.gridLayout_4.addWidget(self.label_gainscale, 7, 0, 1, 1)
        self.checkBox_20k = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_20k.setObjectName("checkBox_20k")
        self.gridLayout_4.addWidget(self.checkBox_20k, 2, 0, 1, 1)
        self.checkBox_200k = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_200k.setObjectName("checkBox_200k")
        self.gridLayout_4.addWidget(self.checkBox_200k, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.checkBox_2k = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_2k.setObjectName("checkBox_2k")
        self.gridLayout_4.addWidget(self.checkBox_2k, 1, 0, 1, 1)
        self.pushButton_abort = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_abort.setObjectName("pushButton_abort")
        self.gridLayout_4.addWidget(self.pushButton_abort, 6, 2, 1, 1)
        self.pushButton_start = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_start.setObjectName("pushButton_start")
        self.gridLayout_4.addWidget(self.pushButton_start, 7, 2, 1, 1)
        self.lineEdit_gainscale = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_gainscale.setObjectName("lineEdit_gainscale")
        self.gridLayout_4.addWidget(self.lineEdit_gainscale, 7, 1, 1, 1)
        self.label_progress = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_progress.setObjectName("label_progress")
        self.gridLayout_4.addWidget(self.label_progress, 0, 2, 1, 1)
        self.label_avgnum = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_avgnum.setObjectName("label_avgnum")
        self.gridLayout_4.addWidget(self.label_avgnum, 5, 0, 1, 1)
        self.lineEdit_dataset = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_dataset.setObjectName("lineEdit_dataset")
        self.gridLayout_4.addWidget(self.lineEdit_dataset, 5, 1, 1, 1)
        self.progressBar_man = QtWidgets.QProgressBar(self.gridLayoutWidget_4)
        self.progressBar_man.setMinimum(0)
        self.progressBar_man.setMaximum(100)
        self.progressBar_man.setProperty("value", 0)
        self.progressBar_man.setObjectName("progressBar_man")
        self.gridLayout_4.addWidget(self.progressBar_man, 4, 2, 1, 1)
        self.pushButton_plot = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_plot.setEnabled(False)
        self.pushButton_plot.setObjectName("pushButton_plot")
        self.gridLayout_4.addWidget(self.pushButton_plot, 5, 2, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 30, 461, 178))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_preamble_count = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_preamble_count.setObjectName("lineEdit_preamble_count")
        self.gridLayout_3.addWidget(self.lineEdit_preamble_count, 1, 1, 1, 1)
        self.lineEdit_preamble_xreference = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_preamble_xreference.setObjectName("lineEdit_preamble_xreference")
        self.gridLayout_3.addWidget(self.lineEdit_preamble_xreference, 5, 1, 1, 1)
        self.lineEdit_preamble_point = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_preamble_point.setObjectName("lineEdit_preamble_point")
        self.gridLayout_3.addWidget(self.lineEdit_preamble_point, 1, 4, 1, 1)
        self.lineEdit_preamble_yreference = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_preamble_yreference.setObjectName("lineEdit_preamble_yreference")
        self.gridLayout_3.addWidget(self.lineEdit_preamble_yreference, 5, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 3, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 5, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 5, 3, 1, 1)
        self.lineEdit_preamble_format = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_preamble_format.setObjectName("lineEdit_preamble_format")
        self.gridLayout_3.addWidget(self.lineEdit_preamble_format, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 3, 1, 1)
        self.lineEdit_preamble_yincrement = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_preamble_yincrement.setObjectName("lineEdit_preamble_yincrement")
        self.gridLayout_3.addWidget(self.lineEdit_preamble_yincrement, 3, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 3, 1, 1)
        self.lineEdit_preamble_xincrement = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_preamble_xincrement.setObjectName("lineEdit_preamble_xincrement")
        self.gridLayout_3.addWidget(self.lineEdit_preamble_xincrement, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 3, 0, 1, 1)
        self.lineEdit_preamble_type = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_preamble_type.setObjectName("lineEdit_preamble_type")
        self.gridLayout_3.addWidget(self.lineEdit_preamble_type, 0, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 6, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 6, 3, 1, 1)
        self.lineEdit_preamble_xorigin = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_preamble_xorigin.setObjectName("lineEdit_preamble_xorigin")
        self.gridLayout_3.addWidget(self.lineEdit_preamble_xorigin, 6, 1, 1, 1)
        self.lineEdit_preamble_yorigin = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_preamble_yorigin.setObjectName("lineEdit_preamble_yorigin")
        self.gridLayout_3.addWidget(self.lineEdit_preamble_yorigin, 6, 4, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 263, 44))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_Time_Begin = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Time_Begin.sizePolicy().hasHeightForWidth())
        self.label_Time_Begin.setSizePolicy(sizePolicy)
        self.label_Time_Begin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Time_Begin.setObjectName("label_Time_Begin")
        self.gridLayout_5.addWidget(self.label_Time_Begin, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_Time_Current = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Time_Current.sizePolicy().hasHeightForWidth())
        self.label_Time_Current.setSizePolicy(sizePolicy)
        self.label_Time_Current.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Time_Current.setObjectName("label_Time_Current")
        self.gridLayout_5.addWidget(self.label_Time_Current, 1, 1, 1, 1)
        self.pushButton_quit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_quit.setGeometry(QtCore.QRect(380, 30, 101, 31))
        self.pushButton_quit.setObjectName("pushButton_quit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 502, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Model"))
        self.label.setText(_translate("MainWindow", "Manufacturer"))
        self.label_3.setText(_translate("MainWindow", "Soft.Version"))
        self.label_SN.setText(_translate("MainWindow", "S/N:"))
        self.label_19.setText(_translate("MainWindow", "PORT:"))
        self.lineEdit_PORT.setText(_translate("MainWindow", "5025"))
        self.lineEdit_IP.setText(_translate("MainWindow", "169.254.133.137"))
        self.label_4.setText(_translate("MainWindow", "IP: "))
        self.label_20.setText(_translate("MainWindow", "Buffer:"))
        self.lineEdit_BUFSIZE.setText(_translate("MainWindow", "4096"))
        self.pushButton_connect.setText(_translate("MainWindow", "connect"))
        self.pushButton_disconnect.setText(_translate("MainWindow", "disconnect"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Configuration"))
        self.pushButton_send_setup.setText(_translate("MainWindow", "Send setup"))
        self.pushButton_select.setText(_translate("MainWindow", "Select"))
        self.pushButton_save.setText(_translate("MainWindow", "save"))
        self.label_5.setText(_translate("MainWindow", "Select your Command file."))
        self.pushButton_send_command.setText(_translate("MainWindow", "Send Command"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Scope Setup"))
        self.radioButton_save.setText(_translate("MainWindow", "Save"))
        self.radioButton_running.setText(_translate("MainWindow", "Running"))
        self.groupBox.setTitle(_translate("MainWindow", "working channel"))
        self.radioButton_ain0.setText(_translate("MainWindow", "CH1"))
        self.radioButton_ain1.setText(_translate("MainWindow", "CH2"))
        self.radioButton_ain2.setText(_translate("MainWindow", "CH3"))
        self.radioButton_ain3.setText(_translate("MainWindow", "CH4"))
        self.lineEdit_datalength.setText(_translate("MainWindow", "10000"))
        self.checkBox_manual.setText(_translate("MainWindow", "Manual"))
        self.lineEdit_200k.setText(_translate("MainWindow", "0"))
        self.label_storeddata.setText(_translate("MainWindow", "STORED DATA"))
        self.lineEdit_20k.setText(_translate("MainWindow", "0"))
        self.lineEdit_man.setText(_translate("MainWindow", "0"))
        self.lineEdit_2k.setText(_translate("MainWindow", "0"))
        self.label_datalength.setText(_translate("MainWindow", "Data Length"))
        self.label_gainscale.setText(_translate("MainWindow", "Gain Scale"))
        self.checkBox_20k.setText(_translate("MainWindow", "20kHz"))
        self.checkBox_200k.setText(_translate("MainWindow", "200kHz"))
        self.label_8.setText(_translate("MainWindow", "Cutoff Freq."))
        self.checkBox_2k.setText(_translate("MainWindow", "2kHz"))
        self.pushButton_abort.setText(_translate("MainWindow", "abort"))
        self.pushButton_start.setText(_translate("MainWindow", "start"))
        self.lineEdit_gainscale.setText(_translate("MainWindow", "92683"))
        self.label_progress.setText(_translate("MainWindow", "Progress"))
        self.label_avgnum.setText(_translate("MainWindow", "Data set"))
        self.lineEdit_dataset.setText(_translate("MainWindow", "10"))
        self.pushButton_plot.setText(_translate("MainWindow", "plot"))
        self.label_16.setText(_translate("MainWindow", "yincrement:"))
        self.label_15.setText(_translate("MainWindow", "xreference:"))
        self.label_9.setText(_translate("MainWindow", "format:"))
        self.label_18.setText(_translate("MainWindow", "yreference:"))
        self.label_10.setText(_translate("MainWindow", "type:"))
        self.label_12.setText(_translate("MainWindow", "point:"))
        self.label_11.setText(_translate("MainWindow", "count:"))
        self.label_13.setText(_translate("MainWindow", "xincrement:"))
        self.label_14.setText(_translate("MainWindow", "xorigin:"))
        self.label_17.setText(_translate("MainWindow", "yorigin:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Nspec"))
        self.label_Time_Begin.setText(_translate("MainWindow", "0000 - 00 - 00 00:00:00"))
        self.label_6.setText(_translate("MainWindow", "BEGIN:"))
        self.label_7.setText(_translate("MainWindow", "working directry"))
        self.label_Time_Current.setText(_translate("MainWindow", "./data/"))
        self.pushButton_quit.setText(_translate("MainWindow", "quit"))

